name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - name: npm install, build and test
      run: |
            sudo add-apt-repository -y ppa:bitcoin/bitcoin
            sudo apt-get update
            sudo apt-get install libdb4.8-dev libdb4.8++-dev -y
    - uses: actions/checkout@v1   
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
