name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - name: install deps
      run: |
            sudo add-apt-repository -y ppa:bitcoin/bitcoin
            sudo apt-get update
            sudo apt-get install libdb4.8-dev libdb4.8++-dev -y
            sudo apt-get install build-essential libtool autotools-dev autoconf pkg-config libssl-dev -y
            sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler -y
            
    - uses: actions/checkout@v1   
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
